# This is a basic workflow to help you get started with Actions

name: Deploy Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]
  #pull_request:
    #branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
#test
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Development
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: View Contents
        run: ls -l

      #- name: Terraform Init
      #  uses: hashicorp/terraform-github-actions/init@v0.4.0
      #  env:
      #    AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      #- name: Terraform Validate
      #  uses: hashicorp/terraform-github-actions/validate@v0.3.7

      #- name: Terraform Apply
      #  uses: hashicorp/terraform-github-actions/apply@v0.4.0
      #  env:
      #    AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
